Repository conveyal/analysis-backend, pull requests merged in 2018-10, with the labels that each got.

#173 Hop Time Fixes
  src/main/java/com/conveyal/taui/models/AddTripPattern.java
  src/main/java/com/conveyal/taui/models/ModificationStop.java
  src/main/java/com/conveyal/taui/models/Reroute.java
Labels: WIP

#171 Store service start and end dates in bundles
  src/main/java/com/conveyal/taui/controllers/BundleController.java
  src/main/java/com/conveyal/taui/controllers/GraphQLController.java
  src/main/java/com/conveyal/taui/controllers/ProjectController.java
  src/main/java/com/conveyal/taui/controllers/TimetableController.java
  src/main/java/com/conveyal/taui/models/AnalysisRequest.java
  src/main/java/com/conveyal/taui/models/Bundle.java
  src/main/java/com/conveyal/taui/models/Region.java
  src/main/java/com/conveyal/taui/persistence/MongoMap.java
Labels: enhancement

#179 Fix NPE that was thrown when the feed ids array was null.
  src/main/java/com/conveyal/taui/models/Modification.java
Labels: bug
